apiVersion: extensions/v1beta1
kind:       Deployment
metadata:
  name: k8-byexamples-spring-rest
  labels:
    app: k8-byexamples-spring-rest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8-byexamples-spring-rest
    spec:
      containers:
        - name:  k8-byexamples-spring-rest
          image: gcr.io/matthewdavis-byexamples/k8-byexamples-spring-rest:1d4c1401c9485ef61322d9f2bb33157951eb351f
          ports:
            - containerPort: 8080
              name:          http
